# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - "3.10-dev"
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
  - "pypy3"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox tox-travis codecov

# Command to run tests, e.g. python setup.py test
script: tox

after_success: codecov
